### ISSUE TITLE
Best integration: iRODS and SweStore

### ISSUE THREAD

**Issue by jhagberg** [UPPMAX/irods#12]
Issue for figure out the best way of integrating iRODS and SweStore. 
Possible ways:
- Universal mass storage system and "arc" commands
- Universal mass storage system and webdav with webdav client, or lftp
- POSIX module and pNFS

**Comment by samuell** [comment]
Yeah, I guess #2 is the one to go for to get going ... while we wait for Jens to fix the #3, afais? (he's working on it, but has limited time).

I have got the u5 server cert added to the test area on Swestore, so I hope to get some progress there soon. Unfortunately I have succeeded to connect with lftp only with rot, but not u5, which is kinda strange. 

Something tells me it could be some nordugrid root certrificate that is missing (or similar), but I haven't yet figured out where I need to add it. Will continue to fight tomorrow ...

**Comment by samuell** [comment]
I havent' yet wrote up the UnivMSS driver template file for lftp yet, so that is a task free to pick for anyone feeling for it :)

**Comment by jhagberg** [comment]
I managed to compile a lftp with openssl. And I can connect. But I got segmentation error when trying to list files. 
Samuel perhaps you can install a openssl verision of lftp? I have not manage to get cadaver to work with ssl either. 
What is the status of pNFS?

**Comment by samuell** [comment]
Cool with some progress ... strange with the segfault ... is it that typical error that we saw before ... something with "message of unknown length received" or something?

Regarding pNFS, I've heard that Jens is working on it now and then, but that it will probably will take some time, so it would indeed be great if we could have some univMSSdriver based solution available before that. But if we don't get lftp to work, we can of course just go on with the arc client as well, to start with, so that we can start getting some experience from the overall iRODS setup ...

**Comment by jhagberg** [comment]
It just segfault with no message what so ever.
Perhaps you can search for a lftp-openssl rpm that is suited for our
linux dist?

Right now In the view of stability the univMSSdriver+arccp looks more
stable than the univMSSdriver+webdavclient...
In the long run pNFS is what we want hopefully.

On Mon, Jan 23, 2012 at 12:52, Samuel Lampa
reply@reply.github.com
wrote:

**Comment by samuell** [comment]
> Right now In the view of stability the univMSSdriver+arccp looks more 
> stable than the univMSSdriver+webdavclient... 
> In the long run pNFS is what we want hopefully.

Fully agree!

Hope the new e-Science cert (as reported per mail) works better!

**Comment by jhagberg** [comment]
I have fixed the e-Science robot cert and now have a working univMSSdriver with local cache.
I upload/download works but delete just delete from iRODS but leave on sweStore. I got a error but I have not figured out what is the problem yet...

**Comment by samuell** [comment]
On Mon, Jan 30, 2012 at 9:41 AM, jhagberg
reply@reply.github.com
wrote:

> I have fixed the e-Science robot cert and now have a working univMSSdriver with local cache.
> I upload/download works but delete just delete from iRODS but leave on sweStore. I got a error but I have not figured out what is the problem yet...

Ok, so somehing strange with the ngrm (or arcrm) command?

// Samuel

**Comment by jhagberg** [comment]
Nothing wrong with arcrm command.
I can delete file manually. 
But error message with iRODS. 
I will work more with debugging.

**Comment by jhagberg** [comment]
irm error:

ERROR: rmUtil: rm error for /testZone1/home/rods/iRODS.backup.20111216.1356.tar.gz, status = -305111 status = -305111 USER_SOCK_CONNECT_ERR, Connection refused

It looks like it not even running the rm command in the bash file...

**Comment by samuell** [comment]
Hmm, strange ... so what does the bash file look like? 
(Maybe you can paste into a gist on gist.github.com?)

**Comment by jhagberg** [comment]
Yes
Here it is with my small debug codes
https://gist.github.com/1712793

**Comment by jhagberg** [comment]
typo:

arcrm -t=5 
should be arcrm -t 30 

But now I got another error I cant put files to sweStore...

**Comment by jhagberg** [comment]
iput -R sweStore irods3.0.tgz 
ERROR: readMsgHeader:header read- read 0 bytes, expect 4, status = -4115
ERROR: readAndProcApiReply: readMsgHeader error. status = -4115 status = -4115 SYS_HEADER_READ_LEN_ERR, Operation now in progress
ERROR: putUtil: put error for /testZone1/home/rods/irods3.0.tgz, status = -4115 status = -4115 SYS_HEADER_READ_LEN_ERR, Operation now in progress
Client Caught broken pipe signal. Connection to server may be down
ERROR: writeMsgHeader: wrote 0 bytes, expect 140, status = -5032

**Comment by jhagberg** [comment]
Looks like iRODS database is full of old garbage.

I can iput new files. but not a file that I before had iput and then irm...
Perhaps We need to purge database or something...

**Comment by samuell** [comment]
Might be useful:
https://www.irods.org/index.php/iRODS_Error_Codes

**Comment by samuell** [comment]
Is the "trash" emptied (as you suggested, Jonas)?

**Comment by jhagberg** [comment]
New error in log file on irm error.

Feb  2 09:04:39 pid:31381 NOTICE: rsAuthCheck user rods#testZone1
Feb  2 09:04:39 pid:31381 NOTICE: rsAuthResponse set proxy authFlag to 5, client authFlag to 5, user:rods#testZone1 proxy:rods client:rods
Feb  2 09:04:40 pid:31381 NOTICE: connectToRhostWithTout: connect error, errno = 111
Feb  2 09:04:40 pid:31381 NOTICE: connectToRhostWithTout: connect error, errno = 103
Feb  2 09:04:40 pid:31381 NOTICE: connectToRhostWithTout: connect error, errno = 111
Feb  2 09:04:40 pid:31381 NOTICE: connectToRhost: connect to host srm.swegrid.se on port 1247 failed, status = -305111 status = -305111 USER_SOCK_CONNECT_ERR, Connection refused
Feb  2 09:04:40 pid:31381 ERROR: _rcConnect: connectToRhost error, server on srm.swegrid.se is probably down status = -305111 USER_SOCK_CONNECT_ERR, Connection refused
Feb  2 09:04:40 pid:31381 NOTICE: dataObjUnlinkS: l3Unlink error for /testZone1/home/rods/iRODS_SRM_Module.tar.gz. status = -305111
Feb  2 09:04:40 pid:31381 NOTICE: dataObjUnlinkS: orphan file /irodstest/home/rods/iRODS_SRM_Module.tar.gz
Feb  2 09:04:40 pid:31381 ERROR: rsMkOrhpanPath: rsCollCreate error for /testZone1/trash/orphan/rods#testZone1 status = -814000 CAT_UNKNOWN_COLLECTION
Feb  2 09:04:40 pid:31381 ERROR: dataObjUnlinkS: svrRegDataObj of orphan /testZone1/trash/orphan/rods#testZone1/iRODS_SRM_Module.tar.gz.2061549280 error status = -814000 CAT_UNKNOWN_COLLECTION
Feb  2 09:04:40 pid:31381 NOTICE: readAndProcClientMsg: received disconnect msg from client
Feb  2 09:04:40 pid:31381 NOTICE: Agent exiting with status = 0

**Comment by jhagberg** [comment]
iadmin lr sweStore
resc_id: 10023
resc_name: sweStore
zone_name: testZone1
resc_type_name: MSS universal driver
resc_class_name: compound
resc_net: srm.swegrid.se
resc_def_path: /irodstest
free_space: 
free_space_ts:  : 1970-01-01.01:00:00
resc_info: 
r_comment: 
resc_status: 
create_ts: 01327668354 : 2012-01-27.13:45:54
modify_ts: 01327668354 : 2012-01-27.13:45:54

**Comment by jhagberg** [comment]
Problem solved with irm. 

iRODS want to connect to net resource. It thinks that it is a another irods server.

I changed the compound resource from srm.swegrid.se to localhost. 
So the line in the wiki should be:

mkresc sweStore 'MSS universal driver' compound localhost /irodstest

I can now delete file from iRODS

**Comment by jhagberg** [comment]
For now this issue is closed. 
Will open new one for future work with pNFS.
