### ISSUE TITLE
bug or problem with arccp 

### ISSUE THREAD

**Issue by jhagberg** [UPPMAX/irods#16]
Issue to my self and project.

arccp command fails if a file already exist on local filesystem. This means that if you have started a transfer with arccp and it gets aborted a empty file with the same filename may exist in local irods cache folder. If you restart the iget command arccp will fail and you will never get your file back... 

the force flag dont work with arccp from swestore to local filesystem...

**Comment by samuell** [comment]
Could it be acceptable to add an rm command before the arccp command runs?
(I guess you can add multiple commands in the function wrappers in the
univMSS file?)

On Wed, Feb 8, 2012 at 12:57 PM, jhagberg
reply@reply.github.com
wrote:

**Comment by jhagberg** [comment]
Good idéa I can add a simple bash check if file exists then delete it before arccp... 

I fix.

**Comment by jhagberg** [comment]
The bash work around is working stable so far.
