### ISSUE TITLE
Install PyRODS @uppmax

### ISSUE THREAD

**Issue by brainstorm** [UPPMAX/irods#19]
In order to test/use PyRods:

http://www.wrg.york.ac.uk/iread/using-the-python-client-side-library

**Comment by jhagberg** [comment]
Is this the same for iRODS 3.1?

**Comment by brainstorm** [comment]
It's a general gcc compiler flag, it should. Just try it ;)

**Comment by jhagberg** [comment]
I have now recompiled u5

in 
config/irods.config 

change setting  to
$CCFLAGS = '-fPIC';

Please have a try!

**Comment by brainstorm** [comment]
No dice :-/

<pre>
(py2.7)[roman@u5 PyRods-3.1.0 0]$ python setup.py build
(...)
g++ -shared build/temp.linux-x86_64-2.6/./src/irods.o build/temp.linux-x86_64-2.6/./src/PyApiNumber.o build/temp.linux-x86_64-2.6/./src/PyAuth.o build/temp.linux-x86_64-2.6/./src/PyChkObjPermAndStat.o build/temp.linux-x86_64-2.6/./src/PyDataObj.o build/temp.linux-x86_64-2.6/./src/PyGetRodsEnv.o build/temp.linux-x86_64-2.6/./src/PyMd5.o build/temp.linux-x86_64-2.6/./src/PyMiscUtil.o build/temp.linux-x86_64-2.6/./src/PyModAccessControl.o build/temp.linux-x86_64-2.6/./src/PyMsParam.o build/temp.linux-x86_64-2.6/./src/PyObf.o build/temp.linux-x86_64-2.6/./src/PyParseCommandLine.o build/temp.linux-x86_64-2.6/./src/PyRcConnect.o build/temp.linux-x86_64-2.6/./src/PyRcMisc.o build/temp.linux-x86_64-2.6/./src/PyRodsAdmin.o build/temp.linux-x86_64-2.6/./src/PyRodsDef.o build/temp.linux-x86_64-2.6/./src/PyRodsError.o build/temp.linux-x86_64-2.6/./src/PyRodsExec.o build/temp.linux-x86_64-2.6/./src/PyRodsFile.o build/temp.linux-x86_64-2.6/./src/PyRodsInfo.o build/temp.linux-x86_64-2.6/./src/PyRodsIO.o build/temp.linux-x86_64-2.6/./src/PyRodsLog.o build/temp.linux-x86_64-2.6/./src/PyRodsMeta.o build/temp.linux-x86_64-2.6/./src/PyRodsPath.o build/temp.linux-x86_64-2.6/./src/PyRodsQuery.o build/temp.linux-x86_64-2.6/./src/PyRodsStructFile.o build/temp.linux-x86_64-2.6/./src/PyRodsUser.o build/temp.linux-x86_64-2.6/./src/PyRodsXmsg.o build/temp.linux-x86_64-2.6/./src/PyStringOpr.o build/temp.linux-x86_64-2.6/./src/sqlMisc.o build/temp.linux-x86_64-2.6/./src/wrapper_misc.o /opt/irods/iRODS//server/core/obj/srvRodsAPIs.a /opt/irods/iRODS//lib/core/obj/libRodsAPIs.a /opt/irods/postgres/pgsql/lib/libodbc.a /opt/irods/iRODS//modules/properties/microservices/obj/propertiesMS.o /opt/irods/iRODS//modules/ERA/microservices/obj/eraUtil.o /opt/irods/iRODS//modules/ERA/microservices/obj/auditMS.o /opt/irods/iRODS//modules/ERA/microservices/obj/eraMS.o /opt/irods/iRODS//modules/ERA/microservices/obj/auditUtil.o /opt/irods/iRODS//modules/ERA/microservices/obj/collInfoMS.o /opt/irods/iRODS//modules/msoDrivers/microservices/obj/msoDboMS.o /opt/irods/iRODS//modules/msoDrivers/microservices/obj/msoHttpMS.o /opt/irods/iRODS//modules/msoDrivers/microservices/obj/msoSlinkMS.o /opt/irods/iRODS//modules/msoDrivers/microservices/obj/msoZ3950MS.o /opt/irods/iRODS//modules/msoDrivers/microservices/obj/msoIrodsMS.o /opt/irods/iRODS//modules/msoDrivers/microservices/obj/msoTestMS.o /opt/irods/iRODS//modules/msoDrivers/microservices/obj/msoSrbMS.o /opt/irods/iRODS//modules/examples/microservices/obj/examplesMS.o -lrt -lstdc++ -o build/lib.linux-x86_64-2.6/irods.so
g++: /opt/irods/iRODS//server/core/obj/srvRodsAPIs.a: No such file or directory
g++: /opt/irods/postgres/pgsql/lib/libodbc.a: Permission denied
</pre>

**Comment by jhagberg** [comment]
Looks like you do not have read access in the postgres folder.

I have tried to build pyrods. Looks like we need to recompile postgres also... 

I will give it a try.

**Comment by jhagberg** [comment]
I have now build PyRODS
following this 
https://groups.google.com/d/msg/irod-chat/JMX3dqoeSXo/vyAeuQQl5DUJ

Changed the setup.py

Please have a look in 
/opt/irods/PyRods-3.1.0

**Comment by brainstorm** [comment]
<pre>
python setup.py build
(...)
g++: /opt/irods/postgres/pgsql/lib/libodbc.so: Permission denied
error: command 'g++' failed with exit status 1
</pre>


Plus if you hit this error and know how to overcome it, followup on the thread:

https://groups.google.com/forum/?fromgroups&hl=sv#!topic/irod-chat/Y0vy7-0-RA8

**Comment by brainstorm** [comment]
Different symbol is missing at uppmax:

<pre>
(py2.7)[roman@u5 PyRods-3.1.0 0]$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/irods/postgres/pgsql/lib
(py2.7)[roman@u5 PyRods-3.1.0 0]$ python
Python 2.7 (r27:82500, Sep  7 2010, 13:19:24) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-48)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import irods
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: roman/.virtualenvs/py2.7/lib/python2.7/site-packages/irods.so: undefined symbol: rcSubStructFileRmdir
</pre>

**Comment by brainstorm** [comment]
From PyRODS README:

<pre>
  You will have an error when you try to do import irods in a python shell
  after installing the package, it will complain for a missing object file for
  the module.
  If all goes well the script parses the config.mk file in the irods directory
  to find which module is linked with the server. It assumes a standard
  hierarchy (modules/modulename/obj/*.o), if this is not the case you will
  have to modify the script.
</pre>

**Comment by brainstorm** [comment]
@jhagberg did:

<pre>
I disabled GSI_auth
make clean
make
rm * in Pyrods build
python setup.py build
</pre>


And worked.
