### ISSUE TITLE
Implement periodic mirroring of LDAP user/group database to ICAT

### ISSUE THREAD

**Issue by samuell** [UPPMAX/irods#21]
Add periodic mirroring of the user/group database into ICAT.

**Comment by samuell** [comment]
I've got the foundation for these scripts already for the irods setup on rot, so I'll be happy to look at this.

**Comment by jhagberg** [comment]
The same script should also set up the file structure and give the right group the right permission on the group.

**Comment by samuell** [comment]
@jhagberg Yep, Indeed, we'll need to remove public access from all proj folders, configure aclpolicy to strict, and add the groups for each project and make those the owners of the proj folders ...

**Comment by samuell** [comment]
JFYI, I'm working on this ... have managed to add all the users (and delete expired ones), so will continue with group membership and project folder etc...

**Comment by jhagberg** [comment]
What is the status of the group sync?

**Comment by samuell** [comment]
I haven't finished it yet, because we had to focus on this git stuff. Will turn to it just about now though.

**Comment by samuell** [comment]
There is code for syncing groups now. Have to make it more robust, and add code for ensuring existance of proj folder now (dependent on #34 )...

**Comment by samuell** [comment]
A crude (but working) script is now active and running twice an hour on kali:
(Code here: https://github.com/UPPMAX/irods/blob/kali/scripts/sync_ldap_to_irods )

**Comment by jhagberg** [comment]
What happens to user owned files when deleting a user?

**Comment by samuell** [comment]
Ah, good question, and point. I guess we should somehow inactivate the users rather than deleting them ...

**Comment by samuell** [comment]
Well, I don't find any way to inactivate iRODS users. Though, as long as we use OS auth, it should not really matter if we leave the users in the DB or not, so for the moment, I have just removed execution of the delete function in crontab.

**Comment by jhagberg** [comment]
But a it would be good to test to delete a user that have files to see what is happening.

**Comment by samuell** [comment]
Maybe we can test this on u5 in a smaller scale then?

**Comment by samuell** [comment]
Have implemented a refined python version [1], and it seem to have stabilized after a few initial bugs. We skip deleting users for now (they are not really ever deleted at UPPMAX anyway, only inactivated).

[1] https://github.com/UPPMAX/irods/blob/kali/scripts/sync_ldap_to_irods.py
