### ISSUE TITLE
30TB cache is full panic rule

### ISSUE THREAD

**Issue by jhagberg** [UPPMAX/irods#22]
If the 30TB cache system is filing up faster than the rule deletes files. It is perhaps a good thing to have a admin rule to delete the oldest file  in cache. 

This rule can be used by admins that manually need to delete files in cache if the file system is filling up to fast.

**Comment by samuell** [comment]
Sounds like a good idea!

Den 27 april 2012 14:45 skrev Jonas Hagberg <
reply@reply.github.com

**Comment by jhagberg** [comment]
I suggest using the itrim command as an admin.
