### ISSUE TITLE
alias iput -K in module files

### ISSUE THREAD

**Issue by samuell** [UPPMAX/irods#27]

**Comment by samuell** [comment]
... to make sure that checksums are calculated.

**Comment by samuell** [comment]
(or better, as @brainstorm suggested, make a wrapper version of it that executes the correct one)

**Comment by jhagberg** [comment]
Looks like irsync is up for the beat now also.

https://groups.google.com/forum/?fromgroups#!topic/iROD-Chat/gMgdVapy77c
https://github.com/irods/irods/commit/da7c42e131a78bcaa6296cd795fb7da531a8e9fd

Very fast to add features for us!

**Comment by samuell** [comment]
Added the alias in the modules now. (also note the new names for the module versions, a la swestore=kali, swestore_old=rot, test=u5).

The wrapper strategy riscs to be overwritten every time we recompile the icommands. I guess we can implement that once we have some build automation system in place (makefile / fabfile or similar ...).

**Comment by jhagberg** [comment]
when irsync -K is availble ? I guess when you merge upstrem irods and compile please add that alias also.

**Comment by samuell** [comment]
Added alias now! (Will have a look at the upstream changes, and maybe update ...)
