### ISSUE TITLE
irsync wrapper

### ISSUE THREAD

**Issue by samuell** [UPPMAX/irods#29]

**Comment by jhagberg** [comment]
@samuell I have added a simple one. 
https://github.com/UPPMAX/irods/commit/05ff6235ef845bb9078ad756350225fa6b9262a9
Can you make some basic test with it and add it to the irods module?

**Comment by samuell** [comment]
Implemented now, as an alias in the module file instead (until we get a proper build system, that can make changes like adding wrappers etc upon compile).
