### ISSUE TITLE
Upgrade to iRODs 3.0

### ISSUE THREAD

**Issue by brainstorm** [UPPMAX/irods#3]
... on biologin.

**Comment by jhagberg** [comment]
I need access do you fix Samuel?

**Comment by samuell** [comment]
Yes! Thanks for the reminder ... has been so busy with other stuff. Will
try to fix tomorrow!

// Samuel

On Wed, Dec 7, 2011 at 7:13 PM, jhagberg <
reply@reply.github.com

**Comment by samuell** [comment]
Just for the record: I tried to compile the 3.0 version on my Ubuntu 11.10 32bit laptop, just to have something to play with, but it failed, so I filed a bug: https://www.irods.org/bugzilla/show_bug.cgi?id=143

(Even more for the record, @jhagberg should have some kind of access to our u5 test machine now.)

**Comment by samuell** [comment]
... and Tore is now reconfiguring the network, so that u5 should soon not be as sluggy as sluggish as it has been.

**Comment by jhagberg** [comment]
Great!

**Comment by jhagberg** [comment]
u5 is now running iRODS 3.0

**Comment by samuell** [comment]
Cool! :)
