### ISSUE TITLE
Request an arcmv command in arc client

### ISSUE THREAD

**Issue by samuell** [UPPMAX/irods#30]
Submitted now: http://bugzilla.nordugrid.org/cgi-bin/bugzilla/show_bug.cgi?id=2854

... keeping this issue open for a while, to keep track ...

**Comment by samuell** [comment]
Duplicate of #28

**Comment by samuell** [comment]
Solution created, and under way :) : http://bugzilla.nordugrid.org/cgi-bin/bugzilla/show_bug.cgi?id=2854

... let's keep the issue open then, until we get it installed ...

**Comment by brainstorm** [comment]
The nordugrid bugzilla seems to be down :-S

According to issue #41, arcmkdir seems to be in place and working well, should we close this issue then?

**Comment by samuell** [comment]
@pontus just installed arcrename on kali, so closing.
