### ISSUE TITLE
Stop execution of move command

### ISSUE THREAD

**Issue by samuell** [UPPMAX/irods#31]
Implement some error message preventing from using mv, until we get a move feature in the arc client
### jhagberg commented 2012-06-11

This could instead be solved by using this core rule
acSetVaultPathPolicy {msiSetRandomScheme; }

That will use random filepath, then mv and rm will only be updates in iCAT.

**Comment by jhagberg** [comment]
@samuell  Can you install srm client on kali? if we are going to use the java based srmmv?

**Comment by samuell** [comment]
Fixed. Binaries now available in /opt/d-cache/srm/bin/!

**Comment by jhagberg** [comment]
We use the java client as a workaround until a other good and UPPMAX approved solution is in place.
