### ISSUE TITLE
Disable and remove home folders

### ISSUE THREAD

**Issue by samuell** [UPPMAX/irods#32]
Disable and remove home folders.

@jhagberg fixes in core rules, so home folders are not created when creating new users.
@samuell removes the existing ones, with a script.

**Comment by jhagberg** [comment]
Changes pushed to branch kali-dev.
Delete all users and re add them or just delete all home folders. 

Is the group sync working? And does the irods module fix where user ends up?

**Comment by samuell** [comment]
Yep, will fix. The group sync is not finished yet. Not big thing to fix though.

Will re-check the module... it might still use "irods" rather than "kali" as hostname...

**Comment by samuell** [comment]
(Module works now, as does group sync, although a bit shaky script ... will polish it now ...)

**Comment by samuell** [comment]
Home folders removed now, since I did a clean install of iRODS after @jhagberg did disable them in core.re.
