### ISSUE TITLE
Implement deployment git infrastructure

### ISSUE THREAD

**Issue by samuell** [UPPMAX/irods#33]
Set up the relevant git repositories, remotes and branches, to enable a workflow where we can automatically pull the latest iRODS version from upstream, as well as merge changes from a development branch to the master (production) in order to implement (and then the production server will do auto pull from the master branch).

Working on this. I have still to find the correct URL to checkout the upstream iRODS version from.

**Comment by samuell** [comment]
After contacting the relevant people at RENCI, we figured the recommended repo to use as upstream is the one at github: https://github.com/irods/irods

Also, I have now created branches u5, u5-dev, kali and kali-dev in our main irods repo. In u5/u5-dev, I also copied in the files and changes that @jhagberg  had made, over the fresh iRODS codebase from upstream.

@jhagberg , so now you can start adding the relevant changes in kali-dev as well, by checking out that branch.

If cloning the iRODS repo afresh, one should be able to do:

```
cd <some-folder>
git clone git@github.com:UPPMAX/irods.git .
git branch -t u5-dev origin/u5-dev
git checkout u5-dev
```

(Check with "git branch" that you are working on the right branch ... there will be an asterisk close to the current one ... )

**Comment by jhagberg** [comment]
Oki so how do we work now? I push all changes to kali-dev?

**Comment by samuell** [comment]
Ah, yes, kali-dev. Sorry, I should have said:

```
cd <some-folder>
git clone git@github.com:UPPMAX/irods.git .
git branch -t kali-dev origin/kali-dev
git checkout kali-dev
# Do changes and stuff ...
git commit -am "Some message"
git push origin kali-dev
```

**Comment by jhagberg** [comment]
Yes but what about the "change" management process? I push to kali-dev you merge with kali? and that is the branch we are running on the production server or?

**Comment by samuell** [comment]
Exactly!

**Comment by samuell** [comment]
Automatic (as per crontab) pull of "kali" branch to /opt/irods is now implemented.
