### ISSUE TITLE
Decide on removing (or not) the zone folder

### ISSUE THREAD

**Issue by samuell** [UPPMAX/irods#34]
By default, iRODS seems to be configured to always use a zone folder as the parent of any custom folder stuctures.

Thus, we have:
/ssUppnexZone/proj/<projfolder>

It would be more convenient for users with:
/proj/<projfolder>

... but this does not play nicely with univMSSInterface.sh. It seems to always remove the most parent folder from paths, so for paths not containing the zone folder, then the next level ("proj" in our case) is removed instead, so that the paths become wrong in the remote location.

**Comment by jhagberg** [comment]
This is just a setting in core.re 
As you can see there is no zone folder on the cache resource either:

cache:   /data/rescs/swestoreArchCacheResc/proj/b2011221/postgresql-9.0.3.tar
swestore: /arch2/proj/b2011221/postgresql-9.0.3.tar

We are trimming one dir with the GRAFT_PATH command

https://github.com/UPPMAX/irods/blob/kali-dev/iRODS/server/config/reConfigs/core.re#L369

If you like to add the zone read the comments and change the "1" to a "0" to not trim any path.

**Comment by samuell** [comment]
Have mailed irod-chat for feedback: https://groups.google.com/d/topic/irod-chat/0gBDK1B0zNI/discussion

**Comment by jhagberg** [comment]
Looks like we need to keep the zone folder. Perhaps we should rename the zone to something that is a bit more easy?

**Comment by samuell** [comment]
Yes, I agree (both to keeping, and renaming :) ). Maybe just "Swestore" ?

**Comment by jhagberg** [comment]
Or just UPPNEX?

**Comment by samuell** [comment]
I was thinking we might want to separate the Swestore storage from other kinds of storage (because it is a bit slower, might have a little bit other policies for backup etc than local storage on UPPMAX, etc), and AFAIS, the best way to separate things in this logical way, is with different zones... isn't it?

**Comment by brainstorm** [comment]
I agree, having two different zones, "swestore" and "uppnex" would definitely help out users on figuring out where they are putting their data. When it comes to federation it feels cleaner as well.

**Comment by samuell** [comment]
There is a problem naming it only "swestore", since it will be ambigious in regard to at least two other possible zones:
- Our own second Swestore zone, for legacy Swestore data
- Swestore's own (probably to appear within the nearest future) iRODS zone/install

Thus, we would need to have a UPPNEX-unique name somehow including Swestore, which still does not get too long. "uppnex-swestore" or "uppnexswestore" is of course a possibility, but is kind of long. Better suggestions would be welcome.

**Comment by brainstorm** [comment]
I would go for simply "swestore" for our new archiving system and then "swestore-legacy" or "swestore-old" for the old archival methods. That will force us to deprecate the "old" zone in favor of the new one, over time, not ASAP.

Otherwise we will end up with a too fragmented namespace, which is discouraged by iRODS philosophy itself and usability reasons.

**Comment by pontus** [comment]
> I would go for simply "swestore" for our new archiving system and then
> "swestore-legacy" or "swestore-old" for the old archival methods. That will
> force us to deprecate the "old" zone in favor of the new one, over time,
> not ASAP.
> 
> Otherwise we will end up with a too fragmented namespace, which is
> discouraged by iRODS philosophy itself and usability reasons.

Just in case that wasn't clear; we expect (warranted or not) the launch of
a central iRODS zone for Swestore that we don't want name collisions with.

**Comment by samuell** [comment]
I think it is quite clear now (based on some mail discussions also) that we should keep the zone folders, to be in line with iRODS conventions.
