### ISSUE TITLE
add irods bash autocomplete in irods module

### ISSUE THREAD

**Issue by jhagberg** [UPPMAX/irods#36]
THere is a bash autocomplete. Can you ad that so that it is sourced when you load the irods module.

**Comment by jhagberg** [comment]
Any updates on this should be a simple fix?

**Comment by pontus** [comment]
AFAICT module has no support for this per se. Added for bash and tcsh (module doesn't seem to work right away for tcsh anyway, but if it does, it'll have completion).

Completion is kinda funky foir the /ssUppnexZone part (inserts an extra / at the beginning, causing things to go haywire), we'll se if that's a nuisance enough to fix.

**Comment by jhagberg** [comment]
I think it works nice if you leave out the zone name!

**Comment by pontus** [comment]
Yeah.

After some investigation, it seems nothing is wrong with the actual completion.

What's happening is that it exposes an internal problem in the irods string handling causing this behaviour:

$ ils //ssUppnexZone/
ERROR: lsUtil: srcPath /ssUppexxZone does not exist or user lacks access permission
$

I'll take it up on irods chat.

**Comment by jhagberg** [comment]
Works for me I start by typing ils /s and it tab completes to:

ils //ssUppnexZone/
/ssUppnexZone:
  C- /ssUppnexZone/home
  C- /ssUppnexZone/proj
  C- /ssUppnexZone/trash

**Comment by jhagberg** [comment]
In any subfolder tab works just fine. 

 ipwd
/ssUppnexZone/proj
[haggan@u5 ~]$ ils ./p2009031/

(just typed ils p <tab> )

**Comment by pontus** [comment]
The first completion from /s works (reasonably) fine, but trying to complete from ils //ssUppnexZone/ yields the same error as above (at least if you're using the same binaries as our users are).

But I'm more afraid about what might happen if someone's made the same error somewhere more important.

**Comment by jhagberg** [comment]
I am running the module on u5
It works just fine also if i start to tab complete from //
and //ssUppnexZone/ 
and I can tab complete all the way down to subfolders in my b2011221 project.

**Comment by pontus** [comment]
GFY. Of course, just because there's a memory related bug it doesn't mean it's always triggered (or triggered the same way on all systems).

It's entirely possible the same binaries we're using on kalkyl (that do have the problem) don't expose the bug if you're username isn't pontusf, or any other random parameter. Either way, the completion stuff works fine, it's ils that breaks.

(I've done a post to irods chat about the problem, we'll se how long it'll be in moderation.)

**Comment by jhagberg** [comment]
I see on on kalkyl I have the same problem.
