### ISSUE TITLE
Irods not able to create envFiles if ~/.irods does not exist

### ISSUE THREAD

**Issue by dahlo** [UPPMAX/irods#37]
I tried to do a icd command, but got the error message

Unable to open envFile /bubo/home/h18/dahlo/.irods/.irodsEnv.4955

Pastebin: http://pastebin.com/mpzgPGJk

Problem was resolved after i manually created ~/.irods

This should be done automatically when you load the irods module.

**Comment by samuell** [comment]
Fixed in the module file!

(This is the tcl code, for reference):

```
if { [file exists ~/.irods] == 0 } {
  file mkdir ~/.irods
}
```
