### ISSUE TITLE
Lower MAX_SZ_FOR_SINGLE_BUF to force parallell transfer mode

### ISSUE THREAD

**Issue by samuell** [UPPMAX/irods#40]
See https://www.irods.org/index.php/iRods_file_transfer

By default, files smaller than 32MB will be transferred in sequential mode from iRODS clients to the server, and the sequential mode always goes via the server that the user connects to and then from this server further to the resource server. 

Only files larger than 32 MB will be done in parallell mode, which connects directly between the client and the resource server.

After implementing iRODS on our new local storage, we would like most accesses to be done directly to the resource servers, so we then need to lower this limit, maybe to 1 or 2MB?

**Comment by jhagberg** [comment]
We only have one server and the resource is located at this server. So there is no need for any change. But perhaps I am missing something here. What are you thinking?

**Comment by samuell** [comment]
Yes,  this was "After implementing iRODS on our new local storage", some 1PB new local storage that we are now installing in the computer room :) Sorry, didn't formulate it very clear.

**Comment by brainstorm** [comment]
For now I would leave the default as it is, we can do some performance tweaking later on... plus if we change default settings now, we'll not have a baseline to compare with :-S

To sum it up: Please, keep it as it is in iRODS and close the issue ;)

**Comment by samuell** [comment]
Going with @brainstorm 's suggestion, so closing this for now.
