### ISSUE TITLE
Problems when using univMSS driver with filenames containing spaces

### ISSUE THREAD

**Issue by pontus** [UPPMAX/irods#43]
The univmssdriver has problems handling filenames with spaces. It doesn't construct an argv and execute the univMSS command directly but constructs a string which is later deconstructed into arguments using space as a delimeter. 

Filenames with spaces will result in multiple arguments, causing the univMSS command to misbehave, even if it handles the parameters it receives correctly.

**Comment by jhagberg** [comment]
Have you made contact to iRODS CHAT?

**Comment by samuell** [comment]
Yes, he has. See https://groups.google.com/forum/?fromgroups=#!topic/iROD-Chat/btlDS1o6O0Q

**Comment by brainstorm** [comment]
In that line, one should mention Swedish characters in filenames and folders (Unicode issues in general), I hope those are handled well by the univMSSdriver... have you tried that?

**Comment by samuell** [comment]
Fix committed by @pontus : https://github.com/UPPMAX/irods/commit/5367217ed53b13685398214ecf16a2449d9fc31a

**Comment by samuell** [comment]
@pontus reports also that files with spaces are visible with arcls after upload, so I suppose we can consider this fixed now.

**Comment by jhagberg** [comment]
Is iRODS compiled with UTF8?

see 
https://groups.google.com/d/msg/iROD-Chat/btlDS1o6O0Q/fTryh0hl8GMJ

have to uncomment: 
#UNI_CODE=1 
in config/config.mk
