### ISSUE TITLE
Add flag for purging cache as alias in module file

### ISSUE THREAD

**Issue by samuell** [UPPMAX/irods#46]
iput has a flag for this. Add in the alias for iput in the module file (our replacement for .irodsEnv).

**Comment by jhagberg** [comment]
--purgec  Purge the staged cache copy after uploading an object to a
     COMPOUND resource

**Comment by jhagberg** [comment]
Perhaps not so good idea if we want fokes to have some time to change their mind or read back file or do i irsync -K again. 
If we purge cache direct and the user use irsync again files will be stage back to cache from swestore for doing a checksum verification.

**Comment by samuell** [comment]
I added this as a temporary solution as long as we have problems with mainly #48 (and maybe #18). We can of course change it later, but at least I'm closing this issue now.

**Comment by jhagberg** [comment]
Added --purgec alias?

**Comment by samuell** [comment]
@jhagberg Yep!
