### ISSUE TITLE
Update arc to a version that contains the arcrename command

### ISSUE THREAD

**Issue by samuell** [UPPMAX/irods#47]

**Comment by samuell** [comment]
@jhagberg started to test this, and reports:

Har checkat ut senaste trunk från arc

```
/home/irods/bin/arc-1.x
```

följer README
kör 

```
./configure --prefix=/home/irods/bin/arcbin
```

Saknar direkt saker. 

```
checking for GTHREAD... configure: error: Package requirements (gthread-2.0 >= 2.4.7) were not met:
No package 'gthread-2.0' found
Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
Alternatively, you may set the environment variables GTHREAD_CFLAGS
and GTHREAD_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

kanske någon av er med mera root skills kan lägga in de beronden som finns och köra om configure tills den inte klagar längre?

**Comment by samuell** [comment]
Installed these packages:

```
glib2-devel
glibmm24-devel
libxml++-devel
...
```

**Comment by jhagberg** [comment]
compile error

auth.cpp:6:35: fel: globus_gsi_credential.h: Filen eller katalogen finns inte

**Comment by jhagberg** [comment]
Can someone with root check and install this packages. Indicated by http://www.nordugrid.org/middleware/build.html

gsoap-devel >= 2.7.2
libxml2-devel >= 2.4.0
globus-common-devel
globus-ftp-client-devel
globus-ftp-control-devel
globus-gass-transfer-devel
globus-gsi-credential-devel
globus-gsi-sysconfig-devel
globus-gss-assist-devel
globus-io-devel
openldap-devel
globus-rls-client-devel
globus-rsl-devel
gettext
python-devel
voms-devel
mysql-devel
bdii
libuuid-devel or e2fsprogs-devel (depending on distribution)

**Comment by samuell** [comment]
@jhagberg , I'll check ...

**Comment by samuell** [comment]
```
gsoap-devel >= 2.7.2 - (missing, installed now)
libxml2-devel >= 2.4.0 - libxml2-devel-2.7.6-4.el6_2.4
globus-common-devel - globus-common-devel-14.6-1.el6
globus-ftp-client-devel - installed 7.3-1.el6 now
globus-ftp-control-devel - installed 4.4-1.el6 now
globus-gass-transfer-devel - 7.2-1.el6 installed
globus-gsi-credential-devel
globus-gsi-sysconfig-devel
globus-gss-assist-devel
globus-io-devel
openldap-devel
globus-rls-client-devel
globus-rsl-devel
gettext
python-devel
voms-devel
mysql-devel
bdii
libuuid-devel or e2fsprogs-devel
```

**Comment by samuell** [comment]
@pontus just installed arcrename on kali, so closing.
