### ISSUE TITLE
Add iRODS/Swestore user documentation to UPPNEX web

### ISSUE THREAD

**Issue by samuell** [UPPMAX/irods#50]
Add iRODS/Swestore user documentation to UPPNEX web, and update or deprecate the old one (https://www.uppnex.uu.se/faq/how-do-i-move-files-national-storage-swestore)

**Comment by samuell** [comment]
Added a new page now, only visible to admins: https://www.uppnex.uu.se/faq/how-i-move-files-swestore-using-irods

**Comment by samuell** [comment]
Draftish draft up (for admins) at http://www.uppnex.uu.se/faq/how-move-files-swestore-using-irods

Will need some peace of mind to refine this to its final state, so that's probly not until tomorrow, fri 14/9.

**Comment by jhagberg** [comment]
Should inform user to use -K and md5sums even if we enforce it.

**Comment by samuell** [comment]
Have informed about the -K flag in the hints section at http://www.uppnex.uu.se/faq/how-move-files-swestore-using-irods#More_hints now.

**Comment by samuell** [comment]
I consider the guide complete enough to close the issue now (even though it can still be polished a lot).
