### ISSUE TITLE
Ensure basic monitoring of kali

### ISSUE THREAD

**Issue by samuell** [UPPMAX/irods#51]
Make sure we have access to basic monitoring of kali. 

Maybe we have nagios already? ... do we need something more? Does nagios check df on the /data volume?

**Comment by jhagberg** [comment]
Perhaps look at scala ? #26

**Comment by samuell** [comment]
We have nagios running for kali. I'm trying to figure out if it is possible to add email alerts for certain events ...

SCALA looks nice. I don't think we'll make it before monday though.

**Comment by samuell** [comment]
I think we have good enough monitoring to get started, so moving this to next milestone.
