### ISSUE TITLE
Patch the iadmin client to support tab completion, editable cmds, cmd history

### ISSUE THREAD

**Issue by samuell** [UPPMAX/irods#7]
I'm going crazy over the unfriendliness of the iadmin client, since it:
- Does not allow tab-completion of commands and params
- Does not let you step backwards with the arrow keys and edit the command
- Does not let you step back in your command line history with the up arrow (if i remember correctly)

Have sent this to the mailing list long ago as a wishlist, but nobody seems to have time to fix this (IMO) serious usability flaw.

**Comment by jhagberg** [comment]
This should be solved in 3.1

"Auto-completion script. There is now an auto-completion script for Bash, irods_completion.bash in the iRODS directory. Thanks to Bruno Bzeznik of the French CIMENT project OAR Team for this contribution"

Please test it out.
